# trunk-ignore-all(yamllint/empty-values)
version: "3.8"

services:
  starknet:
    image: nethermind/juno:v0.11.1
    ports:
      - 6060:6060
    volumes:
      - ${HOME}/code/kkrt-labs/snapshots/juno_sepolia:/var/lib/juno
    command: >
      --pending-poll-interval "1s"
      --http
      --http-host 0.0.0.0
      --http-port 6060
      --db-path /var/lib/juno
      --eth-node ${ETH_NODE_WS}
      --network sepolia
    networks:
      - internal
  starknet-explorer:
    image: public.ecr.aws/o5q6k5w4/stark_compass_explorer:latest
    ports:
      - 4000:4000
    environment:
      - PHX_HOST=localhost
      - PORT=4000
      - RPC_API_HOST=http://host.docker.internal:6060
      - TESTNET_RPC_API_HOST=http://host.docker.internal:6060
      - SEPOLIA_RPC_API_HOST=http://host.docker.internal:6060
      - DISABLE_MAINNET_SYNC=true
      - DISABLE_SEPOLIA_SYNC=true
      - DATABASE_PATH=ecto://postgres:postgres@starknet-explorer-db:5432/starknet_explorer_dev
      - DB_TYPE=postgres
      - SECRET_KEY_BASE=JyULoT5cLBifW+XNEuCTVoAb+SaFgQt9j227RN0cKpR3wTsrApGd1HNcgeopemyl
      - ENABLE_LISTENER=true
    depends_on:
      starknet-explorer-db:
        condition: service_started
      starknet:
        condition: service_started
    extra_hosts:
      - host.docker.internal:172.17.0.1
    networks:
      - internal

  starknet-explorer-db:
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=starknet_explorer_dev
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - starknet_explorer_staging:/var/lib/postgresql/data/

  kakarot-rpc:
    image: eliastazartes/kakarot-rpc:v0.5.1
    pull_policy: always
    ports:
      - 3030:3030
    environment:
      - KAKAROT_RPC_URL=0.0.0.0:3030
      - STARKNET_NETWORK=http://starknet:6060
      - RUST_LOG=kakarot_rpc=info
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DATABASE_NAME=kakarot-local
      # These values are unique to Sepolia Testnet
      # They'll need to be manually changed in case the testnet is reset
      # To add robustness: parse the `deployments/starknet-sepolia` folder in `kkrt-labs/kakarot` repo
      - KAKAROT_ADDRESS=0x94a7535a2867b444b03dfd6cfb61324a0a915bd224cfb9a23f36f2fb4116ad
      - UNINITIALIZED_ACCOUNT_CLASS_HASH=0x1d8b8047e26b484d3f6262d1967217d980d0f2dfc69afa5661492bd5bfe2954
      - ACCOUNT_CONTRACT_CLASS_HASH=0x6344933b8e462a570c09cd011a6207ca9eb07b183cda4639581eaa8e428e043
    restart: on-failure
    depends_on:
      starknet:
        condition: service_started
    networks:
      - internal

  apibara-dna:
    extends:
      file: docker-compose.yaml
      service: apibara-dna
    command:
      - start
      - --rpc=http://starknet:6060
      - --wait-for-rpc
      - --data=/data

  ### MongoDB with Mongo Express
  mongo:
    extends:
      file: docker-compose.yaml
      service: mongo

  clone-repo:
    extends:
      file: docker-compose.yaml
      service: clone-repo

  indexer:
    image: quay.io/apibara/sink-mongo:0.7.0
    command:
      - run
      - /code/kakarot-indexer/src/main.ts
    environment:
      # Whitelist environment variables
      - ALLOW_ENV_FROM_ENV=DEBUG,APIBARA_AUTH_TOKEN,STARTING_BLOCK,STREAM_URL,SINK_TYPE,MONGO_CONNECTION_STRING,MONGO_DATABASE_NAME,STARKNET_NETWORK,KAKAROT_ADDRESS,ALLOW_NET,MONGO_REPLACE_DATA_INSIDE_TRANSACTION
      - DEBUG=""
      - APIBARA_AUTH_TOKEN=""
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DATABASE_NAME=kakarot-local
      - STARTING_BLOCK=0
      - STREAM_URL=http://apibara-dna:7171
      - SINK_TYPE=mongo
      - STARKNET_NETWORK=http://starknet:6060
      - ALLOW_NET=
      - MONGO_REPLACE_DATA_INSIDE_TRANSACTION=true
      - KAKAROT_ADDRESS=0x94a7535a2867b444b03dfd6cfb61324a0a915bd224cfb9a23f36f2fb4116ad
    restart: on-failure
    volumes:
      - indexer_code:/code
    networks:
      - internal
    depends_on:
      clone-repo:
        condition: service_completed_successfully
      starknet:
        condition: service_started

networks:
  internal:
    driver: bridge
  default:
    driver: bridge
  close:
    driver: bridge

volumes:
  apibara:
  mongo_data:
  indexer_code:
  pgadmin_data:
  starknet_explorer_staging:
  juno_files_staging:
