# trunk-ignore-all(checkov/CKV2_GHA_1)
on:
  # trunk-ignore(yamllint/empty-values)
  workflow_call:

jobs:
  build:
    # trunk-ignore(actionlint/runner-label)
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 120
    steps:
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      # Load submodules
      - name: Load submodules
        id: cached-submodules
        uses: actions/cache/restore@v3
        with:
          path: ./lib/
          key: ${{ runner.os }}-submodules
      # Install Foundry
      - name: install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      # Install Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      # Make Setup
      - name: Setup the Kakarot submodule
        run: make setup
      # Store artifacts of the build of both Kakarot and the contract ABIs
      - name: Upload Contract Builds
        uses: actions/upload-artifact@v3
        with:
          name: kakarot-build
          path: ./lib/kakarot/build/**/*.json
          if-no-files-found: error
          retention-days: 1
      - name: Upload ABIs
        uses: actions/upload-artifact@v3
        with:
          name: contract-abis
          path: ./artifacts/**/*.json
          if-no-files-found: error
          retention-days: 1
