name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest-16-cores
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust env
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: llvm-tools-preview
          override: true
          toolchain: 1.73.0
      - name: Retrieve cached dependencies
        uses: Swatinem/rust-cache@v2
      - name: Setup coverage env
        uses: taiki-e/install-action@cargo-llvm-cov
      # nextest setup
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      # Load lib submodules
      - name: Load submodules
        id: cached-submodules
        uses: actions/cache/restore@v3
        with:
          path: ./lib/
          key: ${{ runner.os }}-submodules
      # Create dump
      - name: Create dump
        run: make build-kakarot && make dump-katana
      - name: Generate code coverage
        run: ./scripts/make_with_env.sh test-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: false
